### PR TITLE
[MRG] a 2022 update - fix many misc things!

### LINKED ISSUE #42: 06_Quality_Control-Python Version Issue
I can not install the khmer software in the dib_rotation environment because of the following error.
> UnsatisfiableError: The following specifications were found
> to be incompatible with the existing python installation in your environment:
> Specifications:
>  - khmer -> python[version='2.7.*|3.5.*|3.6.*|>=3.6,<3.7.0a0|>=3.8,<3.9.0a0|>=3.7,<3.8.0a0|>=3.5,<3.6.0a0|>=2.7,<2.8.0a0|3.4.*']
> Your python: python=3.10

The solution provided by Taylor Reiter that worked for me was to create a separate `khmer` env:
> what i would do is create a new env just for the khmer step
> `conda deactivate dib_rotation`
> `conda create -n khmer khmer`
> `conda activate khmer`
> and then run the khmer commands in that env, then switch back to `dib_rotation env` when that step is done

Cheers,
Colton

### LINKED ISSUE #43: 07_taxonomic_discovery_with_sourmash
In 07_taxonomic_discovery_with_sourmash at the lca gather step and I receive this error:
> (dib_rotation) baumlerc@bm12:~/2020_rotation_project/sourmash$ ls
> genbank-k31.lca.json   SRR1976948_2.fastq.gz
> SRR1976948_1.fastq.gz  SRR1976948.sig
> 
> (dib_rotation) baumlerc@bm12:~/2020_rotation_project/sourmash$ sourmash lca gather -o SRR1976948_lca_gather.csv
> SRR1976948.sig genbank-k31.lca.json
> lca: error: argument subcmd: invalid choice: 'gather' (choose from 'classify', 'compare', 'compare_csv', 'index', 'rankinfo', 'summarize')

The work around suggested by Dr Titus Brown:
> you’ll get decent results from `sourmash gather` but it won’t be the same.
> (that is, just omit the `lca`)

### LINKED ISSUE #44: 07_taxonomic_discovery_with_sourmash compute > sketch
Please update the `sourmash compute` command to `sourmash sketch dna`.

This is an updated command which allows for a more flexible way to build signatures.

Vest,
Colton

### PR DESCRIPTION
**Pull request by ctb**
Fix many issues. Also -

* merges `00_getting_started` into `index` (they were already identical) and puts `index` in the TOC;
* rewrites things to use mamba instead of conda in most places. 

- [x] This should fix #42 by pinning python to 3.8 but we need to verify that.
- [x] This should fix #43 by switching to gather but we should also update the output (and maybe the database used - switch to GTDB?)
- [x] This should fix #44 and #46 by switching sourmash compute to sourmash sketch, but the command needs to be verified

Fixes https://github.com/dib-lab/dib_rotation/issues/34
Fixes https://github.com/dib-lab/dib_rotation/issues/41
Fixes https://github.com/dib-lab/dib_rotation/issues/42
Fixes https://github.com/dib-lab/dib_rotation/issues/43
Fixes https://github.com/dib-lab/dib_rotation/issues/44
Fixes https://github.com/dib-lab/dib_rotation/issues/45 by installing mamba up front
Fixes https://github.com/dib-lab/dib_rotation/issues/46

Note that early attempts to pin the `dib_rotation` conda environment to python=3.8 ran afoul of [this problem](https://github.com/mamba-org/mamba/issues/1583) where conda installs a very old version of mamba when python=3.8! So I ended up installing mamba in base.

cc @ccbaumler

### CODE REVIEW

**Comment by ctb** [comment]
we need to manually update the mkdocs site, right @bluegenes ?

**Comment by bluegenes** [comment]
> we need to manually update the mkdocs site, right @bluegenes ?

No, I think the GitHub actions should automatically deploy the site, as long as the markdown syntax is good!

**Comment by ctb** [comment]
@ccbaumler have you taken a look at these changes? any comments or concerns?

**Comment by ccbaumler** [comment]
Hi @ctb,

I am not noticing anything glaring but if you would like I can work through the entire website again this week to find any remaining typos or possible areas of improvement.

Respectfully,
Colton

**Pull request merged**
